sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env:
        - COMPOSER_ARGUMENTS=--prefer-lowest
    - php: 5.6
      env:
        - EXECUTE_TEST_COVERALLS=true
    - php: 7.0
      env:
        - EXECUTE_CS_CHECK=true
    - php: hhvm

before_install:
  - if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then phpenv config-rm xdebug.ini || return 0; fi

install:
  - travis_retry composer update --no-interaction $COMPOSER_ARGUMENTS
  - composer info -i

script:
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then composer test-coverage -- --colors=always; fi
  - if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then composer test -- --colors=always; fi

  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then composer cs-check -- --ansi; fi

after_script:
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then
    travis_retry wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar;
    chmod +x coveralls.phar;
    travis_retry php coveralls.phar --verbose;
    fi
